<h3><b>Introduction to Data Analytics - Exercise set 1 - Python and NumPy Basics</b></h3>

Put all your exercises (Jupyter Notebooks or Python-files) in your course Git-project.<br /><br />
<span style="font-weight: bold;">Use either code comments or Jupyter Notebook markdown (text) to document which exercise you are doing and what a certain code section does!</span><br />

<span style="font-weight: bold;">Remember: your Jupyter notebook's clarity (how easy it is to read and understand) also affects your scoring!</span><br /><br />
<span style="font-weight: bold;">Remember also: 
<span style="font-weight: bold;">If you use generative AI in any part of any exercise, 
MENTION IT CLEARLY! </span><br />
<span style="font-weight: bold;">(code comments are enough, also mention the prompts used).</span><br /><br />
See also the materials discussing the usage of AI in this course!</span><br /><br />


You can return all of these exercises in a single Jupyter Notebook, if you wish.

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/numpylogo.png" width="250"/>

<b>NOTE!</b> For each subtask, save the result into a separate variable!

In [53]:
# setup all needed modules and configurations
import numpy as np

<b>We can change the default Jupyter style for NumPy arrays by overriding the display formatter:</b>

In [54]:
# RUN THIS CODE CELL IN ORDER TO USE THE CUSTOM STYLES
from IPython.core.interactiveshell import InteractiveShell

# Custom HTML formatter for NumPy arrays
# you can customize the color's if you wish!
# NOTE: this can be a bit buggy with some 
# more advanced NumPy operations, try removing
# this custom formatting code if problems arise

# NOTE: you can control the amount of decimals by changing 
# precision value below (9 is enough for the NumPy exercises)
def array_to_html(arr, precision=9):
    # Round the numbers to the specified precision and convert to string
    str_arr = np.round(arr, precision).astype(str)
    
    # Find the maximum width (longest string length)
    max_width = max([len(val) for val in str_arr.flatten()])
    
    # Create the HTML table with consistent column width and centered text
    html = "<table style='border: 1px solid black; border-collapse: collapse;'>"
    
    if arr.ndim == 1:
        # Handle 1D array (vector)
        for val in str_arr:
            html += f"<tr><td style='padding: 5px; border: 1px solid black; font-weight: bold; width: {max_width}ch; text-align: center;'>{val}</td></tr>"
    else:
        # Handle 2D array (matrix)
        for row in str_arr:
            html += "<tr>"
            for val in row:
                html += f"<td style='padding: 5px; border: 1px solid black; font-weight: bold; width: {max_width}ch; text-align: center;'>{val}</td>"
            html += "</tr>"
    
    html += "</table>"
    return html

# Register the formatter in IPython
InteractiveShell.instance().display_formatter.formatters['text/html'].for_type(
    np.ndarray, lambda arr: array_to_html(arr)
)

# Usage as usual from now on
data = np.arange(0, 9).reshape(3, 3)
data


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

<h4><b>1. Create these lists without NumPy:</b></h4>

- List of 15 ones

- List of 15 number 7's

- List of numbers from 100 to 150

- List of even numbers between 0 and 100

- List of years that are divisible by 4 between 1950 and 2020

<br>

<b>Tip: creating a list with Python code is usually something like this:</b>

<pre>
numbers = []

for x in range(0, 5):
    numbers.append(x)
</pre>

In [55]:
# exercise 1.1, create lists without NumPy
# use additional code cells or different variable names for each subtask
numbers = []

for x in range(0,15):
  numbers.append(1)

print(numbers)
print(f"The length of the list: {len(numbers)}")


[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
The length of the list: 15


In [56]:
# Creating a list of fifteen 7's in a list
numbers = []

for x in range(0, 15):
  numbers.append(7)

print(numbers)
print(f"The length of the list: {len(numbers)}")

[7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]
The length of the list: 15


In [57]:
# Creating a list of numbers from 100 to 150.
numbers = []

for i in range(100,151):
  numbers.append(i)

print(numbers)
print(f"The length of the list: {len(numbers)}")

[100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150]
The length of the list: 51


In [58]:
# A list of even numbers between 0 and 100
numbers = []

for i in range(0,101):
  if i % 2 == 0:
    numbers.append(i)

print(numbers)


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [59]:
# A list of years divisible by 4 in range 1950-2020
numbers = []
for i in range(1950,2021):
  if i % 4 == 0:
    numbers.append(i)
    
print(numbers)

[1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988, 1992, 1996, 2000, 2004, 2008, 2012, 2016, 2020]


<h4><b>2.	Now, create these arrays with NumPy!</b></h4>

- Array of 15 zeroes

- Array of 15 ones

- Array of 15 number 7's

- Array of numbers from 100 to 150

- Array of numbers from 1900 to 2021

- Array of even numbers between 0 and 100

- Array of years that are divisible by 4 between 1950 and 2020



In [60]:
# exercise 1.2, create lists WITH NumPy
# use additional code cells or different variable names for each subtask

# An array of 15 zeroes.
numbers = np.zeros(15)
numbers
print(f"The amount of entries in the list: {len(numbers)}")


The amount of entries in the list: 15


In [61]:
# An array of 15 ones.
numbers = np.ones(15)
numbers
print(f"The amount of entries in the list: {len(numbers)}")

The amount of entries in the list: 15


In [62]:
# An array of 15 number 7's.
numbers = np.ones(15).astype(int)*7
numbers
print(f"The amount of entries in the list: {len(numbers)}")

The amount of entries in the list: 15


In [63]:
# Array of numbers from 100 to 150.
numbers = np.arange(0,151)

# Uses print (since it's 1-Dimensional.)
print(numbers)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150]


In [64]:
# Array of numbers from 1900 to 2021.
numbers = np.arange(1900,2022)

# Uses print (since it's 1-Dimensional.)
print(numbers)

[1900 1901 1902 1903 1904 1905 1906 1907 1908 1909 1910 1911 1912 1913
 1914 1915 1916 1917 1918 1919 1920 1921 1922 1923 1924 1925 1926 1927
 1928 1929 1930 1931 1932 1933 1934 1935 1936 1937 1938 1939 1940 1941
 1942 1943 1944 1945 1946 1947 1948 1949 1950 1951 1952 1953 1954 1955
 1956 1957 1958 1959 1960 1961 1962 1963 1964 1965 1966 1967 1968 1969
 1970 1971 1972 1973 1974 1975 1976 1977 1978 1979 1980 1981 1982 1983
 1984 1985 1986 1987 1988 1989 1990 1991 1992 1993 1994 1995 1996 1997
 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011
 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021]


In [65]:
# Array of even numbers between 0 and 100. (the two means step-2.)
numbers = np.arange(0,101,2)

# Using print (since it's 1-Dimensional.)
print(numbers)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [66]:
# Array of years that are divisble by 4 between 1950 and 2020.
numbers = np.arange(1952,2021,4)

# Using print (since it's 1-Dimensional.)
print(numbers)

[1952 1956 1960 1964 1968 1972 1976 1980 1984 1988 1992 1996 2000 2004
 2008 2012 2016 2020]


<h4><b style="color: red">Note: compare the NumPy code to the plain Python code after doing the exercises. Easier or more difficult? :) 
(answer in code comments or as text in Jupyter Notebook)</b></h4>

---

### My thoughts about the difference between Exercise 1 and 2 (plain Python and NumPy):

It's much easier to use NumPy, particularly because it's faster and it doesn't require loops! 

It is a worthy mention, however, that the NumPy's arange step begins from the starting value, not the number division.

<br>

Example: 

*Array of years that are divisble by 4 between 1950 and 2020*


`numbers = np.arange(1950,2021,4)`

` [1950,1954,1958, ...]`

<br>

This is **not correct**, since the step count of 4 is relative from the **starting value, not from the number itself.** I will have to take note of that as I continue to learn NumPy!


---


<h3><b>3. Let's try out NumPy vectors and matrices:</b></h3>

- Create a NumPy vector (list) containing these values:<br>
<b><i>5, 16, 9, 2, 19, 18, 11, 7</i></b><br>
    - Use argmax() to find the position index of the largest value in the vector, and print it
<br><br>
- Create a 7x7 matrix, with values from 1 to 49

    - Extra task: Create this matrix (list of lists) without NumPy in Python! <b>(Without the help of AI!)</b>

<br>

- Generate 8x8 random number matrix, values between 0 and 5

- Generate 8x8 random number matrix, using standard normal distribution values (= values are between -3 and 3)


In [67]:
# A NumPy vector (list) containing these values: 5, 16, 9, 2, 19, 18, 11, 7.
numbers = [5, 16, 9, 2, 19, 18, 11, 7]
data = np.array(numbers)

# gives the index of the highest value in the array.
max_value_position = data.argmax()

print(f"The index of the highest value in the array: {max_value_position}")


The index of the highest value in the array: 4


In [68]:
# Create a 7x7 matrix, with the values from 1 to 49.
numbers = np.arange(1,50).reshape(7,7)
numbers

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [69]:
# Extra Task!
# Create the same matrix, 1-49, 7x7, in Python!

# This strategy uses the incrementor to count from 1 - 49.
data = []
increment = 1

# For each row, it makes an empty list and fills it with the
# Increment number above seven times.
for r in range(1,8):
  row = []

  for i in range(1,8):
   row.append(increment)
   # It then adds 1 to increment, so it can call the next number.
   increment += 1

  # Finally, it adds the row to the matrix list.
  data.append(row)
data

[[1, 2, 3, 4, 5, 6, 7],
 [8, 9, 10, 11, 12, 13, 14],
 [15, 16, 17, 18, 19, 20, 21],
 [22, 23, 24, 25, 26, 27, 28],
 [29, 30, 31, 32, 33, 34, 35],
 [36, 37, 38, 39, 40, 41, 42],
 [43, 44, 45, 46, 47, 48, 49]]

In [70]:
# Generate a 8x8 random number matrix with the values between 0 and 5 for each row.append
data = np.random.randint(0,5, 64).reshape(8,8)
data

array([[0, 0, 1, 4, 1, 1, 2, 0],
       [0, 0, 4, 1, 1, 1, 3, 4],
       [3, 0, 2, 2, 4, 1, 4, 4],
       [2, 2, 1, 0, 2, 1, 2, 0],
       [1, 2, 2, 3, 1, 4, 2, 4],
       [2, 4, 4, 1, 4, 4, 3, 2],
       [1, 3, 2, 1, 4, 2, 1, 1],
       [3, 1, 3, 1, 4, 2, 1, 1]], dtype=int32)

In [71]:
# Generating a 8x8 random number matrix, using standard normal distribution values (= values are between -3 and 3)
data = np.random.randn(8,8)
np.round(data,2)

array([[ 1.47, -1.53,  1.85, -0.02,  0.34, -0.13,  0.82,  0.99],
       [-0.01, -0.98,  1.03,  1.38,  0.07, -0.73,  1.46,  0.44],
       [ 0.56, -0.88,  0.15, -0.82,  1.29, -2.97,  0.54,  0.14],
       [-0.15,  0.78, -0.96, -1.08,  2.39,  0.58,  0.52, -1.04],
       [-0.16,  0.65,  0.01,  0.63, -0.47,  0.36, -1.52,  0.19],
       [ 0.15, -1.03, -0.42,  0.42,  0.3 , -0.08,  0.73,  0.21],
       [ 0.02,  0.27, -0.79, -0.85, -1.09, -0.78, -0.54,  0.44],
       [ 0.04,  0.27,  0.27, -0.7 , -0.89, -0.79,  0.38, -0.16]])

<h3><b>4. Create a linearly spaced… </b></h3>

- array (list/vector) of 10 values between value 0 and 1

- 10x10 matrix between values 0 and 5

    - Extra task: create this matrix without NumPy as well! <b>(Without the help of AI!)</b>


<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/cubes.png"/>


In [72]:
# Create a linearly-spaced array (list/vector) of 10 values between value 0 and 1.
data = np.linspace(0,1,10)
data = data.round(2)
print(data)


[0.   0.11 0.22 0.33 0.44 0.56 0.67 0.78 0.89 1.  ]


In [73]:
# Create linearly-spaced array, 10x10 matrix between values 0 and 5.
data = np.linspace(0,5, 100).reshape(10,10)
np.round(data,2)

array([[0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45],
       [0.51, 0.56, 0.61, 0.66, 0.71, 0.76, 0.81, 0.86, 0.91, 0.96],
       [1.01, 1.06, 1.11, 1.16, 1.21, 1.26, 1.31, 1.36, 1.41, 1.46],
       [1.52, 1.57, 1.62, 1.67, 1.72, 1.77, 1.82, 1.87, 1.92, 1.97],
       [2.02, 2.07, 2.12, 2.17, 2.22, 2.27, 2.32, 2.37, 2.42, 2.47],
       [2.53, 2.58, 2.63, 2.68, 2.73, 2.78, 2.83, 2.88, 2.93, 2.98],
       [3.03, 3.08, 3.13, 3.18, 3.23, 3.28, 3.33, 3.38, 3.43, 3.48],
       [3.54, 3.59, 3.64, 3.69, 3.74, 3.79, 3.84, 3.89, 3.94, 3.99],
       [4.04, 4.09, 4.14, 4.19, 4.24, 4.29, 4.34, 4.39, 4.44, 4.49],
       [4.55, 4.6 , 4.65, 4.7 , 4.75, 4.8 , 4.85, 4.9 , 4.95, 5.  ]])

In [74]:
# Extra task!
# Create this matrix without NumPy as well! (without the help of AI!)
# We will use a similar method to the last extra exercise.
data = []
incrementer = 1

# it creates an empty row and then fills it with 10 numbers for each row.
# then it adds the row into data. 
for row in range(1,11):
  row = []

  # Similar to slope-intercept form (Y=mx+b), the incrementor moves up each iteration.
  for n in range(1,11):
    number = (incrementer / 100) * 5
    row.append(round(number,2))
    incrementer += 1

  data.append(row)
print(data)

[[0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5], [0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 1.0], [1.05, 1.1, 1.15, 1.2, 1.25, 1.3, 1.35, 1.4, 1.45, 1.5], [1.55, 1.6, 1.65, 1.7, 1.75, 1.8, 1.85, 1.9, 1.95, 2.0], [2.05, 2.1, 2.15, 2.2, 2.25, 2.3, 2.35, 2.4, 2.45, 2.5], [2.55, 2.6, 2.65, 2.7, 2.75, 2.8, 2.85, 2.9, 2.95, 3.0], [3.05, 3.1, 3.15, 3.2, 3.25, 3.3, 3.35, 3.4, 3.45, 3.5], [3.55, 3.6, 3.65, 3.7, 3.75, 3.8, 3.85, 3.9, 3.95, 4.0], [4.05, 4.1, 4.15, 4.2, 4.25, 4.3, 4.35, 4.4, 4.45, 4.5], [4.55, 4.6, 4.65, 4.7, 4.75, 4.8, 4.85, 4.9, 4.95, 5.0]]


A clearer output(because the above output is hard to read/grade):

In [75]:
# since above game a horrible visual, here is a better output.
data = np.array(data)
np.round(data,2)


array([[0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ],
       [0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ],
       [1.05, 1.1 , 1.15, 1.2 , 1.25, 1.3 , 1.35, 1.4 , 1.45, 1.5 ],
       [1.55, 1.6 , 1.65, 1.7 , 1.75, 1.8 , 1.85, 1.9 , 1.95, 2.  ],
       [2.05, 2.1 , 2.15, 2.2 , 2.25, 2.3 , 2.35, 2.4 , 2.45, 2.5 ],
       [2.55, 2.6 , 2.65, 2.7 , 2.75, 2.8 , 2.85, 2.9 , 2.95, 3.  ],
       [3.05, 3.1 , 3.15, 3.2 , 3.25, 3.3 , 3.35, 3.4 , 3.45, 3.5 ],
       [3.55, 3.6 , 3.65, 3.7 , 3.75, 3.8 , 3.85, 3.9 , 3.95, 4.  ],
       [4.05, 4.1 , 4.15, 4.2 , 4.25, 4.3 , 4.35, 4.4 , 4.45, 4.5 ],
       [4.55, 4.6 , 4.65, 4.7 , 4.75, 4.8 , 4.85, 4.9 , 4.95, 5.  ]])

<h3><b>5. Recreate the matrices in code based on the pictures.</b></h3>

- Create this 3x5 matrix with NumPy:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix1.png"/>


Note: The values above have no logic, you'll have to feed basic Python lists to NumPy for this result


In [76]:
# exercise 1.5a, create matrix
numbers = [23, 34, 54, 31, 75, 33, 56, 78,65, 97, 41, 32, 11, 39, 51]
numbers = np.array(numbers).reshape(3,5)
numbers


array([[23, 34, 54, 31, 75],
       [33, 56, 78, 65, 97],
       [41, 32, 11, 39, 51]])

- Generate this NumPy array:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix2.png" width="800"/>

In [77]:
# exercise 1.5b, generate NumPy array / matrix
numbers = np.arange(128, 256).reshape(8,16)
numbers


array([[128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
        141, 142, 143],
       [144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
        157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172,
        173, 174, 175],
       [176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188,
        189, 190, 191],
       [192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204,
        205, 206, 207],
       [208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
        221, 222, 223],
       [224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236,
        237, 238, 239],
       [240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252,
        253, 254, 255]])

- Generate this NumPy array:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix3.png" width="500"/>

<b>Tips:</b> arange-function (and step-parameter) + reshape is recommended. Alternatively you can use broadcasting and division if you like.

In [78]:
# exercise 1.5c, generate NumPy array / matrix
data = np.arange(0.05,5.05,.05).reshape(10,10)
np.round(data,2)


array([[0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ],
       [0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ],
       [1.05, 1.1 , 1.15, 1.2 , 1.25, 1.3 , 1.35, 1.4 , 1.45, 1.5 ],
       [1.55, 1.6 , 1.65, 1.7 , 1.75, 1.8 , 1.85, 1.9 , 1.95, 2.  ],
       [2.05, 2.1 , 2.15, 2.2 , 2.25, 2.3 , 2.35, 2.4 , 2.45, 2.5 ],
       [2.55, 2.6 , 2.65, 2.7 , 2.75, 2.8 , 2.85, 2.9 , 2.95, 3.  ],
       [3.05, 3.1 , 3.15, 3.2 , 3.25, 3.3 , 3.35, 3.4 , 3.45, 3.5 ],
       [3.55, 3.6 , 3.65, 3.7 , 3.75, 3.8 , 3.85, 3.9 , 3.95, 4.  ],
       [4.05, 4.1 , 4.15, 4.2 , 4.25, 4.3 , 4.35, 4.4 , 4.45, 4.5 ],
       [4.55, 4.6 , 4.65, 4.7 , 4.75, 4.8 , 4.85, 4.9 , 4.95, 5.  ]])

<h3><b>6. Use this matrix in your code:</b></h3>

dataset = np.arange(1, 37).reshape(6, 6)

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix4.png"/>


In [79]:
# exercise 1.6a, matrix slicing
dataset = np.arange(1, 37).reshape(6, 6)
dataset

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

- Create a slice of the matrix that contains this part of the matrix:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix5.png"/>

In [80]:
# exercise 1.6b, matrix slicing
subset = np.vsplit(dataset, 2)

# splits the the second half of the subset and splits it 3 ways vertically.
subset = np.hsplit(subset[1], 3)

# combines the second and third part of the subset that we need for the output.
subset = np.hstack((subset[1], subset[2]))
subset


array([[21, 22, 23, 24],
       [27, 28, 29, 30],
       [33, 34, 35, 36]])

- Pick out this column slice from data

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/series1.png"/>

In [81]:
# exercise 1.6c, matrix slicing
# creates a subset of the original dataset
subset = dataset

# splits the subset line by line 
subset = np.hsplit(subset,6)

# Takes the fourth column, and splits that three-ways.
subset = np.vsplit(subset[3],3)

# vertically stack the first two vsplits. 
subset = np.vstack((subset[0], subset[1]))
subset


array([[ 4],
       [10],
       [16],
       [22]])

- Pick out this row from the data

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/series2.png"/>

In [82]:
# exercise 1.6d, matrix slicing
# creates a subset of the original data
subset = dataset

# splits the data horizonally, 6 ways.
subset = np.vsplit(subset,6)

# unravels the data
subset = subset[2].ravel()

# and reforms the data into a single column.
subset = subset.reshape(6,1)
subset

array([[13],
       [14],
       [15],
       [16],
       [17],
       [18]])

- Pick out these three rows from data:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix6.png"/>

In [83]:
# exercise 1.6e, matrix slicing
# creates a subset of the original data.
subset = dataset

# splits the data in 2 rows
subset = np.vsplit(subset,2)

# renames the second half of the split as the subset
subset = subset[1]
subset 

array([[19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

<h3><b>7. Use this matrix:</b></h3>

<b>dataset_2 = np.arange(1, 50).reshape(7, 7)</b>

- Add 50 to all values in the array (use broadcasting)

- Get the sum of all values in the dataset
    - <b>Use this version of the data in the following steps!</b>

- Get sum of only odd numbers in the dataset

- Get the standard deviation of the values in the dataset

- Get the sum of all values by ROW in the dataset

- Get the sum of all values by COLUMN in the dataset (tip, use the axis –parameter)

<br>

- <b>Extra task:</b> Do the total sum, row sum and column sum exercises <u><b>without</b></u> NumPy in Python! <b>(Without the help of AI!)</b>

<br>
<b>Note:</b> Don't create a new dataset when adding 50 to all values in the array, use the existing one.
<br><br>
<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/desktopcomputer.png"/>


In [84]:
# exercise 1.7, NumPy -operations on a matrix
dataset_2 = np.arange(1, 50).reshape(7, 7)

# use different variable names for each subtask
# you can also make new code cells if you need

# Adding 50 to all values in the array (using broadcasting)
dataset = dataset + 50
dataset

array([[51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68],
       [69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80],
       [81, 82, 83, 84, 85, 86]])

In [85]:
# Getting the sum of all values in the subset
total = np.sum(dataset)
total 

np.int64(2466)

In [86]:
# Getting the standard deviation of all the values in the subset.
deviation = np.std(dataset)
print(deviation)

10.388294694831615


In [87]:
# Adding together all the rows in the subset.
sum_rows= np.sum(dataset, axis=1)
print(sum_rows)

[321 357 393 429 465 501]


In [88]:
# Adding together all the columns in the subset.
sum_columns = np.sum(dataset, axis=0)
print(sum_columns)

[396 402 408 414 420 426]


In [89]:
# Extra Task!
# Re-doing all the tasks above without NumPy.

# Sum of all columns.
sum_columns = sum(dataset)
print(sum_columns)

[396 402 408 414 420 426]


In [90]:
# Sum of rows!
sum_rows = []
amount = len(dataset)

# iterates each row via the range of the length of the subset (7 rows)
for i in range(amount):
  sum_rows.append(sum(dataset[i]))
print(sum_rows)

[np.int64(321), np.int64(357), np.int64(393), np.int64(429), np.int64(465), np.int64(501)]


In [91]:
# optionally, one can do this to output a normal list:
sum_rows = [int(x) for x in sum_rows]
sum_rows

[321, 357, 393, 429, 465, 501]

In [92]:
# sum_all will tally/store all of the numbers, which is iterated column by column.
sum_all = 0
amount = len(dataset)

# iterates each row via the range of the length of the subset (7 rows)
for i in range(amount):

  # it takes the sum of the column, and adds it to sum_all.
  sum_all += sum(dataset[i])
int(sum_all)

2466

<br><br>
<h2><b>Advanced extra tasks for extra points (varying challenges, some require Googling):</b></h2>

<h3><b>1. Create two files for this exercise: save_matrix.py and read_matrix.py</b></h3>

- in save_matrix.py: create a 15x15 matrix, and save it to a file (matrix.txt)
 - in read_matrix.py, read matrix.txt, and convert it back to a NumPy matrix

NumPy has loadtxt() and savetxt()-functions for these purposes.


In [93]:
# advanced extra exercise 1
matrix = np.random.rand(5,5)
np.round(matrix,2)

array([[0.16, 0.46, 0.83, 0.69, 0.46],
       [0.79, 0.05, 0.43, 0.45, 0.97],
       [0.71, 0.1 , 0.89, 0.27, 0.35],
       [0.9 , 0.81, 0.39, 0.74, 0.85],
       [0.25, 0.43, 0.3 , 0.73, 0.01]])

In [94]:
np.savetxt('matrix.txt', matrix, delimiter =', ')
matrix = np.loadtxt('matrix.txt', matrix, delimiter =', ')
np.round(matrix,2)

TypeError: Cannot construct a dtype from an array

<h3><b>2. Masked arrays are a feature of NumPy that allow us to deal with pieces data that are incorrect or missing in a dataset (for example, faulty measurements from equipment etc.).</b></h3>

Create a NumPy matrix, that contains numbers between 0 to 50, and put some faulty numbers in a 10 different spots 
(for example: -100)

Use a masked array to handle the -100 values in your matrix. Replace every -100 with 0.


In [ ]:
# advanced extra exercise 2


<h3><b>3. argsort is a feature of NumPy  that allows you to sort a NumPy array based on another NumPy array. </b></h3>

This is useful if you have two separate arrays, but their data  should be in sync even if order of data is changed. For example, one array contains the prices of cars, and another contains the manufacturing years. If we wish to sort the data by manufacturing years, and keep the prices in sync as well, argsort will be handy.

Useful link:
http://arogozhnikov.github.io/2015/09/29/NumpyTipsAndTricks1.html

Create two random datasets:

- Manufacturing years of 10 cars, values between 2010 and 2020

- Selling price of 10 cars, prices between 2000€ and 60000€

Use argsort to sort both datasets according to manufacturing years.


In [ ]:
# advanced extra exercise 3


<h3><b>4. Try out the following additional NumPy features, and discuss in your code comments or in Jupyter Notebook text where they could be useful. You can also Google and search for ideas where these could be used. </b></h3>

You can write your thoughts as comments in the code or Jupyter text as you try out each feature.

- np.repeat()

- np.ravel()

- np.hsplit(), np.vsplit(), np.hstack, np.vstack()

- np.transpose()

- np.round()

- np.expand_dims(), np.squeeze()

- np.digitize()




In [ ]:
# advanced extra exercise 4
