<h3><b>Introduction to Data Analytics - Exercise set 1 - Python and NumPy Basics</b></h3>

Put all your exercises (Jupyter Notebooks or Python-files) in your course Git-project.<br /><br />
<span style="font-weight: bold;">Use either code comments or Jupyter Notebook markdown (text) to document which exercise you are doing and what a certain code section does!</span><br />

<span style="font-weight: bold;">Remember: your Jupyter notebook's clarity (how easy it is to read and understand) also affects your scoring!</span><br /><br />
<span style="font-weight: bold;">Remember also: 
<span style="font-weight: bold;">If you use generative AI in any part of any exercise, 
MENTION IT CLEARLY! </span><br />
<span style="font-weight: bold;">(code comments are enough, also mention the prompts used).</span><br /><br />
See also the materials discussing the usage of AI in this course!</span><br /><br />


You can return all of these exercises in a single Jupyter Notebook, if you wish.

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/numpylogo.png" width="250"/>

<b>NOTE!</b> For each subtask, save the result into a separate variable!

<b>We can change the default Jupyter style for NumPy arrays by overriding the display formatter:</b>

In [62]:
# RUN THIS CODE CELL IN ORDER TO USE THE CUSTOM STYLES
from IPython.core.interactiveshell import InteractiveShell
from __future__ import print_function
import numpy as np
import numpy.ma as ma

# Custom HTML formatter for NumPy arrays
# you can customize the color's if you wish!
# NOTE: this can be a bit buggy with some 
# more advanced NumPy operations, try removing
# this custom formatting code if problems arise

# NOTE: you can control the amount of decimals by changing 
# precision value below (9 is enough for the NumPy exercises)
def array_to_html(arr, precision=9):
    # Round the numbers to the specified precision and convert to string
    str_arr = np.round(arr, precision).astype(str)
    
    # Find the maximum width (longest string length)
    max_width = max([len(val) for val in str_arr.flatten()])
    
    # Create the HTML table with consistent column width and centered text
    html = "<table style='border: 1px solid black; border-collapse: collapse;'>"
    
    if arr.ndim == 1:
        # Handle 1D array (vector)
        for val in str_arr:
            html += f"<tr><td style='padding: 5px; border: 1px solid black; font-weight: bold; width: {max_width}ch; text-align: center;'>{val}</td></tr>"
    else:
        # Handle 2D array (matrix)
        for row in str_arr:
            html += "<tr>"
            for val in row:
                html += f"<td style='padding: 5px; border: 1px solid black; font-weight: bold; width: {max_width}ch; text-align: center;'>{val}</td>"
            html += "</tr>"
    
    html += "</table>"
    return html

# Register the formatter in IPython
InteractiveShell.instance().display_formatter.formatters['text/html'].for_type(
    np.ndarray, lambda arr: array_to_html(arr)
)



<function __main__.<lambda>(arr)>

<h4><b>1. Create these lists without NumPy:</b></h4>

- List of 15 ones

- List of 15 number 7's

- List of numbers from 100 to 150

- List of even numbers between 0 and 100

- List of years that are divisible by 4 between 1950 and 2020

<br>

<b>Tip: creating a list with Python code is usually something like this:</b>

<pre>
numbers = []

for x in range(0, 5):
    numbers.append(x)
</pre>

In [63]:
# Exercise 1a
# List of 15 ones.
numbers = []

for x in range(0,15):
  numbers.append(1)

print(numbers)
print(f"The length of the list: {len(numbers)}")


[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
The length of the list: 15


In [64]:
# Question 1b
# List of fifteen 7's in a list
numbers = []

for x in range(0, 15):
  numbers.append(7)

print(numbers)
print(f"The length of the list: {len(numbers)}")

[7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]
The length of the list: 15


In [65]:
# Question 1c
# Creating a list of numbers from 100 to 150.
numbers = []

for i in range(100,151):
  numbers.append(i)

print(numbers)
print(f"The length of the list: {len(numbers)}")

[100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150]
The length of the list: 51


In [66]:
# Question 1d
# A list of even numbers between 0 and 100
numbers = []

for i in range(0,101):
  if i % 2 == 0:
    numbers.append(i)

print(numbers)


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [67]:
# Question 1e
# A list of years divisible by 4 in range 1950-2020
numbers = []

for i in range(1950,2021):
  if i % 4 == 0:
    numbers.append(i)
    
print(numbers)

[1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988, 1992, 1996, 2000, 2004, 2008, 2012, 2016, 2020]


<h4><b>2.	Now, create these arrays with NumPy!</b></h4>

- Array of 15 zeroes

- Array of 15 ones

- Array of 15 number 7's

- Array of numbers from 100 to 150

- Array of numbers from 1900 to 2021

- Array of even numbers between 0 and 100

- Array of years that are divisible by 4 between 1950 and 2020



In [68]:
# Exercise 2

# create lists WITH NumPy
# use additional code cells or different variable names for each subtask
# An array of 15 zeroes.
numbers = np.zeros(15)
print(f"Amount of zeroes in the array: {len(numbers)}")
numbers

Amount of zeroes in the array: 15


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [69]:
# Question 2a
# An array of 15 ones.
numbers = np.ones(15)
print(f"Amount of ones in the array: {len(numbers)}")
numbers


Amount of ones in the array: 15


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [70]:
# Question 2b
# An array of 15 number 7's.
numbers = np.ones(15).astype(int)*7
print(f"Amount of sevens in the array: {len(numbers)}")
numbers


Amount of sevens in the array: 15


array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [71]:
# Question 2c
# Array of numbers from 100 to 150.
numbers = np.arange(100,151)
numbers

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [72]:
# Question 2d
# Array of numbers from 1900 to 2021.
numbers = np.arange(1900,2022)

# Uses print (since it's 1-Dimensional.)
numbers

array([1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910,
       1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921,
       1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932,
       1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943,
       1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954,
       1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965,
       1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976,
       1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987,
       1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998,
       1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009,
       2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020,
       2021])

In [73]:
# Question 2e
# Array of even numbers between 0 and 100. (the two means step-2.)
numbers = np.arange(0,101,2)

# Using print (since it's 1-Dimensional.)
numbers

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [74]:
# Question 2f
# Array of years that are divisble by 4 between 1950 and 2020.
numbers = np.arange(1952,2021,4)

# Using print (since it's 1-Dimensional.)
numbers

array([1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988, 1992,
       1996, 2000, 2004, 2008, 2012, 2016, 2020])

<h4><b style="color: red">Note: compare the NumPy code to the plain Python code after doing the exercises. Easier or more difficult? :) 
(answer in code comments or as text in Jupyter Notebook)</b></h4>
See below

---

### My thoughts about the difference between Exercise 1 and 2 (plain Python and NumPy):

It's much easier to use NumPy compared to python, particularly because it's faster and it doesn't require loops.
It is a worthy mention, however, that the NumPy's arange step begins from the starting value, not the number division.

Example: 
*Array of years that are divisble by 4 between 1950 and 2020*

`numbers = np.arange(1950,2021,4)`

` [1950,1954,1958, ...]`

<br>

This almost caught me off guard!, since the step count of 4 is relative from the **starting value, not from the number itself.**


---


<h3><b>3. Let's try out NumPy vectors and matrices:</b></h3>

- Create a NumPy vector (list) containing these values:<br>
<b><i>5, 16, 9, 2, 19, 18, 11, 7</i></b><br>
    - Use argmax() to find the position index of the largest value in the vector, and print it
<br><br>
- Create a 7x7 matrix, with values from 1 to 49

    - Extra task: Create this matrix (list of lists) without NumPy in Python! <b>(Without the help of AI!)</b>

<br>

- Generate 8x8 random number matrix, values between 0 and 5

- Generate 8x8 random number matrix, using standard normal distribution values (= values are between -3 and 3)

In [75]:
# Exercise 3a
# A NumPy vector (list) containing these values: 5, 16, 9, 2, 19, 18, 11, 7.
numbers = [5, 16, 9, 2, 19, 18, 11, 7]
data = np.array(numbers)

In [76]:
# Using argmax() to find the position of the largest value.
max_value_position = data.argmax()

print(f" The index of highest value: {max_value_position}")

 The index of highest value: 4


In [77]:
# Question 3b
# Create a 7x7 matrix, with the values from 1 to 49.
numbers = np.arange(1,50).reshape(7,7)
numbers

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [78]:
# Question 3c
# Extra Task!
# Create the same matrix, 1-49, 7x7, in plain Python!

# This method uses an incrementor to count from 1 - 49.
data = []
increment = 1

# For each row, it makes an empty list and fills it with the
# Increment number above seven times.
for r in range(1,8):
  row = []

  for i in range(1,8):
   row.append(increment)
   # It then adds 1 to increment, so it can call the next number.
   increment += 1

  # Finally, it adds the row to the matrix list.
  data.append(row)
data

[[1, 2, 3, 4, 5, 6, 7],
 [8, 9, 10, 11, 12, 13, 14],
 [15, 16, 17, 18, 19, 20, 21],
 [22, 23, 24, 25, 26, 27, 28],
 [29, 30, 31, 32, 33, 34, 35],
 [36, 37, 38, 39, 40, 41, 42],
 [43, 44, 45, 46, 47, 48, 49]]

In [79]:
# Question 3d
# Generate a 8x8 random number matrix with the values between 0 and 5
data = np.random.randint(0,5, 64).reshape(8,8)
data

array([[2, 3, 4, 2, 2, 1, 2, 1],
       [3, 4, 2, 4, 0, 2, 4, 2],
       [1, 1, 3, 0, 3, 1, 2, 1],
       [4, 1, 0, 4, 0, 4, 1, 0],
       [2, 1, 3, 3, 1, 2, 4, 0],
       [4, 0, 1, 4, 3, 0, 4, 1],
       [1, 0, 4, 3, 2, 4, 2, 0],
       [3, 3, 0, 2, 2, 3, 1, 1]], dtype=int32)

In [80]:
# Question 3e
# Generating a 8x8 random number matrix, using standard normal distribution values (= values are between -3 and 3)
data = np.random.randn(8,8)
np.round(data,2)

array([[ 0.28,  0.14,  0.95,  0.58, -0.76,  0.18, -0.21,  2.1 ],
       [-1.49, -0.65, -0.71,  1.15,  1.5 , -0.33,  0.83, -1.26],
       [ 0.49,  0.03, -0.39,  0.17,  2.19, -0.05,  0.24,  0.28],
       [-0.83,  0.34,  0.59,  0.12, -0.96,  0.25, -0.9 ,  1.87],
       [ 1.03, -0.55,  0.44, -0.26,  1.55,  0.49,  0.07,  0.44],
       [ 0.59,  1.48, -1.14, -0.15, -1.19,  0.55,  0.64, -0.53],
       [ 2.42,  0.24, -1.44, -0.05, -0.95, -0.06, -0.53,  0.51],
       [ 0.74, -0.02,  0.44, -0.08,  1.05, -0.71,  1.03, -0.82]])

<h3><b>4. Create a linearly spaced… </b></h3>

- array (list/vector) of 10 values between value 0 and 1

- 10x10 matrix between values 0 and 5

    - Extra task: create this matrix without NumPy as well! <b>(Without the help of AI!)</b>


<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/cubes.png"/>


In [81]:
# Exercise 4a

# Create a linearly-spaced array (list/vector) of 10 values between value 0 and 1.
data = np.linspace(0,1,10)
data = data.round(2)

print(f"Amount of numbers in array: {len(data)}")
data


Amount of numbers in array: 10


array([0.  , 0.11, 0.22, 0.33, 0.44, 0.56, 0.67, 0.78, 0.89, 1.  ])

In [82]:
# Question 4b
# Create linearly-spaced array, 10x10 matrix between values 0 and 5.
data = np.linspace(0,5, 100).reshape(10,10)
np.round(data,2)

array([[0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45],
       [0.51, 0.56, 0.61, 0.66, 0.71, 0.76, 0.81, 0.86, 0.91, 0.96],
       [1.01, 1.06, 1.11, 1.16, 1.21, 1.26, 1.31, 1.36, 1.41, 1.46],
       [1.52, 1.57, 1.62, 1.67, 1.72, 1.77, 1.82, 1.87, 1.92, 1.97],
       [2.02, 2.07, 2.12, 2.17, 2.22, 2.27, 2.32, 2.37, 2.42, 2.47],
       [2.53, 2.58, 2.63, 2.68, 2.73, 2.78, 2.83, 2.88, 2.93, 2.98],
       [3.03, 3.08, 3.13, 3.18, 3.23, 3.28, 3.33, 3.38, 3.43, 3.48],
       [3.54, 3.59, 3.64, 3.69, 3.74, 3.79, 3.84, 3.89, 3.94, 3.99],
       [4.04, 4.09, 4.14, 4.19, 4.24, 4.29, 4.34, 4.39, 4.44, 4.49],
       [4.55, 4.6 , 4.65, 4.7 , 4.75, 4.8 , 4.85, 4.9 , 4.95, 5.  ]])

In [83]:
# Question 4
# Extra task!
# Create this matrix without NumPy as well! (without the help of AI!)

# We will use an incrementer method similar to the last extra exercise.
data = []
incrementer = 0

# it creates an empty row and then fills it with 10 numbers for each row.
# then it adds the row into data. 
for row in range(1,11):
  row = []

  # Similar to slope-intercept form (Y=mx+b), the incrementor moves up each iteration.
  for n in range(1,11):
    number = (incrementer / 100) * 5
    row.append(number)
    incrementer += 1

  data.append(row)

# the output in numpy for easier visualization
# otherwise, use print(data)
data = np.array(data)
data



array([[0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45],
       [0.5 , 0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95],
       [1.  , 1.05, 1.1 , 1.15, 1.2 , 1.25, 1.3 , 1.35, 1.4 , 1.45],
       [1.5 , 1.55, 1.6 , 1.65, 1.7 , 1.75, 1.8 , 1.85, 1.9 , 1.95],
       [2.  , 2.05, 2.1 , 2.15, 2.2 , 2.25, 2.3 , 2.35, 2.4 , 2.45],
       [2.5 , 2.55, 2.6 , 2.65, 2.7 , 2.75, 2.8 , 2.85, 2.9 , 2.95],
       [3.  , 3.05, 3.1 , 3.15, 3.2 , 3.25, 3.3 , 3.35, 3.4 , 3.45],
       [3.5 , 3.55, 3.6 , 3.65, 3.7 , 3.75, 3.8 , 3.85, 3.9 , 3.95],
       [4.  , 4.05, 4.1 , 4.15, 4.2 , 4.25, 4.3 , 4.35, 4.4 , 4.45],
       [4.5 , 4.55, 4.6 , 4.65, 4.7 , 4.75, 4.8 , 4.85, 4.9 , 4.95]])

<h3><b>5. Recreate the matrices in code based on the pictures.</b></h3>

- Create this 3x5 matrix with NumPy:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix1.png"/>


Note: The values above have no logic, you'll have to feed basic Python lists to NumPy for this result


In [84]:
# Exercise 5a

#  Create the matrix above.
numbers = [23, 34, 54, 31, 75, 33, 56, 78, 65, 97, 41, 32, 11, 39, 51]
numbers = np.array(numbers).reshape(3,5)
numbers


array([[23, 34, 54, 31, 75],
       [33, 56, 78, 65, 97],
       [41, 32, 11, 39, 51]])

- Generate this NumPy array:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix2.png" width="800"/>

In [85]:
# Question 5b
# Create the matrix above.
numbers = np.arange(128, 256).reshape(8,16)
numbers

array([[128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
        141, 142, 143],
       [144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
        157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172,
        173, 174, 175],
       [176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188,
        189, 190, 191],
       [192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204,
        205, 206, 207],
       [208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
        221, 222, 223],
       [224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236,
        237, 238, 239],
       [240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252,
        253, 254, 255]])

- Generate this NumPy array:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix3.png" width="500"/>

<b>Tips:</b> arange-function (and step-parameter) + reshape is recommended. Alternatively you can use broadcasting and division if you like.

In [86]:
# Question 5c
# Create the matrix above
data = np.arange(0.05,5.05,.05).reshape(10,10)
np.round(data,2)


array([[0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ],
       [0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ],
       [1.05, 1.1 , 1.15, 1.2 , 1.25, 1.3 , 1.35, 1.4 , 1.45, 1.5 ],
       [1.55, 1.6 , 1.65, 1.7 , 1.75, 1.8 , 1.85, 1.9 , 1.95, 2.  ],
       [2.05, 2.1 , 2.15, 2.2 , 2.25, 2.3 , 2.35, 2.4 , 2.45, 2.5 ],
       [2.55, 2.6 , 2.65, 2.7 , 2.75, 2.8 , 2.85, 2.9 , 2.95, 3.  ],
       [3.05, 3.1 , 3.15, 3.2 , 3.25, 3.3 , 3.35, 3.4 , 3.45, 3.5 ],
       [3.55, 3.6 , 3.65, 3.7 , 3.75, 3.8 , 3.85, 3.9 , 3.95, 4.  ],
       [4.05, 4.1 , 4.15, 4.2 , 4.25, 4.3 , 4.35, 4.4 , 4.45, 4.5 ],
       [4.55, 4.6 , 4.65, 4.7 , 4.75, 4.8 , 4.85, 4.9 , 4.95, 5.  ]])

<h3><b>6. Use this matrix in your code:</b></h3>

dataset = np.arange(1, 37).reshape(6, 6)

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix4.png"/>


In [87]:
# Exercise 5d

# Creating the matrix.
dataset = np.arange(1, 37).reshape(6, 6)
dataset

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

- Create a slice of the matrix that contains this part of the matrix:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix5.png"/>

In [88]:
# Question 5e
dataset[3:6, 2:6]



array([[21, 22, 23, 24],
       [27, 28, 29, 30],
       [33, 34, 35, 36]])

- Pick out this column slice from data

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/series1.png"/>

In [89]:
# Question 5f

# Create the matrix above via slicing
dataset[0:4, 3]

array([ 4, 10, 16, 22])

- Pick out this row from the data

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/series2.png"/>

In [90]:
# Question 5g

# creates a subset of the original data
dataset[2,0:]

array([13, 14, 15, 16, 17, 18])

- Pick out these three rows from data:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix6.png"/>

In [91]:
# Question 5h
# using vsplit to get some practice! (and for fun)

# creates a subset of the original data.
subset = dataset

# splits the data in 2 rows
subset = np.vsplit(subset,2)

# renames the second half of the split as the subset
subset = subset[1]
subset 

array([[19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

<h3><b>7. Use this matrix:</b></h3>

<b>dataset_2 = np.arange(1, 50).reshape(7, 7)</b>

- Add 50 to all values in the array (use broadcasting)

- Get the sum of all values in the dataset
    - <b>Use this version of the data in the following steps!</b>

- Get sum of only odd numbers in the dataset

- Get the standard deviation of the values in the dataset

- Get the sum of all values by ROW in the dataset

- Get the sum of all values by COLUMN in the dataset (tip, use the axis –parameter)

<br>

- <b>Extra task:</b> Do the total sum, row sum and column sum exercises <u><b>without</b></u> NumPy in Python! <b>(Without the help of AI!)</b>

<br>
<b>Note:</b> Don't create a new dataset when adding 50 to all values in the array, use the existing one.
<br><br>
<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/desktopcomputer.png"/>


In [92]:
# Exercise 7

# NumPy -operations on a matrix
# Creating the  dataset
dataset_2 = np.arange(1, 50).reshape(7, 7)


# Question 7a

# Adding 50 to all values in the array (using broadcasting)
dataset_2 = dataset_2 + 50
dataset_2

array([[51, 52, 53, 54, 55, 56, 57],
       [58, 59, 60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78],
       [79, 80, 81, 82, 83, 84, 85],
       [86, 87, 88, 89, 90, 91, 92],
       [93, 94, 95, 96, 97, 98, 99]])

In [93]:
# Question 7b

# Getting the sum of all values in the subset
total = np.sum(dataset_2)
print(f"Sum: {total}") 

Sum: 3675


In [94]:
# Question 7c

# getting the sum of only all the odd numbers in the dataset
odds = dataset_2[dataset_2 % 2 == 1]
odd_sum = np.sum(odds)
print(f"Sum of all odd numbers in dataset: {odd_sum}")


Sum of all odd numbers in dataset: 1875


In [95]:
# Question 7d

# Getting the standard deviation of all the values in the subset.
deviation = np.std(dataset_2)
print(f"STD: {deviation.round(3)}")

STD: 14.142


In [96]:
# Question 7e

# Adding together all the rows in the subset.
sum_rows= np.sum(dataset_2, axis=1)
print(f"Sum-rows: {sum_rows}")
sum_rows

Sum-rows: [378 427 476 525 574 623 672]


array([378, 427, 476, 525, 574, 623, 672])

In [97]:
# Question 7f

# Adding together all the columns in the subset.
sum_columns = np.sum(dataset_2, axis=0)
print(f"Sum-columns: {sum_columns}")
sum_columns

Sum-columns: [504 511 518 525 532 539 546]


array([504, 511, 518, 525, 532, 539, 546])

In [98]:
# Question 7b, 7e, 7d (Plain Python)

# Extra Task!
# Re-doing total-sum, row-sum, and column-sum without NumPy.


# Recreating sum-columns.
sum_columns = sum(dataset)
print(sum_columns)
sum_columns

[ 96 102 108 114 120 126]


array([ 96, 102, 108, 114, 120, 126])

In [99]:
# Recreating sum-rows using a for loop.
sum_rows = []
amount = len(dataset)

# iterates each row via the range(len) of the rows.
for i in range(amount):
  sum_rows.append(sum(dataset[i]))
  

# printing the rows using using list comprehension.
print("Sum of each row by index: ")
sum_rows = [int(x) for x in sum_rows]
sum_rows

Sum of each row by index: 


[21, 57, 93, 129, 165, 201]

In [100]:
# sum_all tallies the numbers, amount is a helper variable.
sum_all = 0
amount = len(dataset)

# iterates each row via the range of the length of the subset (7 rows)
for i in range(amount):

  # adds the sum of the column to sum_all 
  sum_all += sum(dataset[i])

print(f"Sum: {sum_all}")

Sum: 666


<br><br>
<h2><b>Advanced extra tasks for extra points (varying challenges, some require Googling):</b></h2>

<h3><b>1. Create two files for this exercise: save_matrix.py and read_matrix.py</b></h3>

- in save_matrix.py: create a 15x15 matrix, and save it to a file (matrix.txt)
 - in read_matrix.py, read matrix.txt, and convert it back to a NumPy matrix

NumPy has loadtxt() and savetxt()-functions for these purposes.


---

Quick Links for easy review

[Click to go to **save_matrix.py**](save_matrix.py)
<br><br>
[Click to go to **read-matrix.py**](read_matrix.py)
<br><br>
[Click to go to **matrix.txt**](matrix.txt)


---

<h3><b>2. Masked arrays are a feature of NumPy that allow us to deal with pieces data that are incorrect or missing in a dataset (for example, faulty measurements from equipment etc.).</b></h3>

Create a NumPy matrix, that contains numbers between 0 to 50, and put some faulty numbers in a 10 different spots 
(for example: -100)

Use a masked array to handle the -100 values in your matrix. Replace every -100 with 0.


In [101]:
# advanced extra exercise 2

# creating numbers between 0 to 50.
data = np.arange(0,50)

# for each 6 spaces, starting from the first element in the index,
# add a faulty number 10 times.
for index in range(10):
  data = np.insert(data, index * 6, -100)

# since the prompt asks for a matrix
# data = data.reshape(10,6)
data.reshape(10,6)


array([[-100,    0,    1,    2,    3,    4],
       [-100,    5,    6,    7,    8,    9],
       [-100,   10,   11,   12,   13,   14],
       [-100,   15,   16,   17,   18,   19],
       [-100,   20,   21,   22,   23,   24],
       [-100,   25,   26,   27,   28,   29],
       [-100,   30,   31,   32,   33,   34],
       [-100,   35,   36,   37,   38,   39],
       [-100,   40,   41,   42,   43,   44],
       [-100,   45,   46,   47,   48,   49]])

In [102]:
# creates a mask from data that says true or false, depending
# on whether it sees if the number is -100
mask = ma.masked_values(data, -100)

# copies the original data 
masked_copy = ma.copy(data)

# applies the mask, which will now show -100 as "---"
masked_copy = np.ma.masked_where(np.ma.getmask(mask), masked_copy)

# replaces "---" with 0
masked_copy = masked_copy.filled(0)
masked_copy.reshape(10,6)

array([[ 0,  0,  1,  2,  3,  4],
       [ 0,  5,  6,  7,  8,  9],
       [ 0, 10, 11, 12, 13, 14],
       [ 0, 15, 16, 17, 18, 19],
       [ 0, 20, 21, 22, 23, 24],
       [ 0, 25, 26, 27, 28, 29],
       [ 0, 30, 31, 32, 33, 34],
       [ 0, 35, 36, 37, 38, 39],
       [ 0, 40, 41, 42, 43, 44],
       [ 0, 45, 46, 47, 48, 49]])

<h3><b>3. argsort is a feature of NumPy  that allows you to sort a NumPy array based on another NumPy array. </b></h3>

This is useful if you have two separate arrays, but their data  should be in sync even if order of data is changed. For example, one array contains the prices of cars, and another contains the manufacturing years. If we wish to sort the data by manufacturing years, and keep the prices in sync as well, argsort will be handy.

Useful link:
http://arogozhnikov.github.io/2015/09/29/NumpyTipsAndTricks1.html

Create two random datasets:

- Manufacturing years of 10 cars, values between 2010 and 2020

- Selling price of 10 cars, prices between 2000€ and 60000€

Use argsort to sort both datasets according to manufacturing years.


In [103]:
# advanced extra exercise 3

# creating two datasets , manufacturer year between 2010 and 2020
# selling price between 2000-60000 euros. 
car_manufacturer_year = np.random.randint(2010,2020,10)
car_selling_price = np.random.randint(2000,60000,10)

# making the sorter, based from manufacturer year!
sorter_by_year = np.argsort(car_manufacturer_year)
car_selling_price[sorter_by_year]

array([25491, 35186, 12541, 31533, 32662, 46450,  5452, 27153, 14573,
       35238], dtype=int32)

In [104]:
car_manufacturer_year[sorter_by_year]

array([2010, 2011, 2013, 2016, 2016, 2017, 2017, 2018, 2019, 2019],
      dtype=int32)

<h3><b>4. Try out the following additional NumPy features, and discuss in your code comments or in Jupyter Notebook text where they could be useful. You can also Google and search for ideas where these could be used. </b></h3>

You can write your thoughts as comments in the code or Jupyter text as you try out each feature.

- np.repeat()

- np.ravel()

- np.hsplit(), np.vsplit(), np.hstack, np.vstack()

- np.transpose()

- np.round()

- np.expand_dims(), np.squeeze()

- np.digitize()




In [105]:
# advanced extra exercise 4
# Below, I'll be going over each feature above I can use them

# np.repeat() is useful for making arrays that make repeated sequences!
# this could be used as an alternative to writing it this way:
# np.ones(4).astype(int) * 3
data = np.repeat(3,4)
data


array([3, 3, 3, 3])

In [106]:
# np.ravel() is the opposite of shape, converting the matrix into an
# array. Let's make a matrix below an unravel it.

# data in matrix form
data = np.repeat(9,9).reshape(3,3)
data

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [107]:
# converting the matrix into an array 
np.ravel(data)

array([9, 9, 9, 9, 9, 9, 9, 9, 9])

In [108]:
# np.hsplit and np.vsplit split up matrices horizontally and
# vertically, respectively. useful for slicing datasets.
# useful for selecting data that you need without any extras.

# creating a new dataset
data = np.random.randint(1,9,100).reshape(10,10)
data

array([[6, 7, 4, 6, 6, 5, 3, 8, 6, 6],
       [6, 6, 7, 7, 3, 7, 3, 4, 4, 3],
       [3, 2, 8, 5, 8, 7, 5, 7, 7, 7],
       [7, 5, 2, 5, 7, 3, 1, 7, 1, 2],
       [8, 7, 8, 7, 4, 7, 8, 6, 3, 2],
       [2, 5, 5, 3, 5, 6, 3, 3, 2, 2],
       [1, 5, 2, 4, 8, 3, 4, 4, 6, 6],
       [4, 3, 5, 2, 8, 1, 3, 6, 1, 3],
       [6, 7, 6, 6, 8, 7, 1, 3, 1, 1],
       [6, 5, 2, 1, 8, 4, 2, 6, 7, 2]], dtype=int32)

In [109]:
# a horizontal split (sliced into two columns.)
data_slice = np.hsplit(data,2)
data_slice[1]

array([[5, 3, 8, 6, 6],
       [7, 3, 4, 4, 3],
       [7, 5, 7, 7, 7],
       [3, 1, 7, 1, 2],
       [7, 8, 6, 3, 2],
       [6, 3, 3, 2, 2],
       [3, 4, 4, 6, 6],
       [1, 3, 6, 1, 3],
       [7, 1, 3, 1, 1],
       [4, 2, 6, 7, 2]], dtype=int32)

In [110]:
# a vertical split (sliced into two rows.)  
data_slice = np.vsplit(data,2)
data_slice[0]

array([[6, 7, 4, 6, 6, 5, 3, 8, 6, 6],
       [6, 6, 7, 7, 3, 7, 3, 4, 4, 3],
       [3, 2, 8, 5, 8, 7, 5, 7, 7, 7],
       [7, 5, 2, 5, 7, 3, 1, 7, 1, 2],
       [8, 7, 8, 7, 4, 7, 8, 6, 3, 2]], dtype=int32)

In [111]:
# np.hstack and np.vstack will combine columns and rows respectively.
# this is great for combining data, but it's important to keep in mind.
# that it needs the same number of cells per row for it to work well!
# these functions are useful for concatenating data.
data_1 = np.array((1,2,3))
data_2 = np.array((4,5,6))

# a horizontal stack.
data_combined = np.hstack((data_1,data_2))
data_combined

array([1, 2, 3, 4, 5, 6])

In [112]:
# a vertical stack
data_combined = np.vstack((data_1,data_2))
data_combined

array([[1, 2, 3],
       [4, 5, 6]])

In [113]:
# np.transpose inverts the x and y axis of a matrix! 
# this might be useful for transforming matrices or arrays that
# have inverted transposition errors.

# creating sample data
data = np.arange(1,10).reshape(3,3)
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [114]:
# np.transpose() to invert the axes.
np.transpose(data)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [115]:
# np.round() rounds the number of each cell. Great for
# making more readable data!

# creating the example data
data = np.linspace(1,10,12).reshape(3,4)
data

array([[ 1.        ,  1.81818182,  2.63636364,  3.45454545],
       [ 4.27272727,  5.09090909,  5.90909091,  6.72727273],
       [ 7.54545455,  8.36363636,  9.18181818, 10.        ]])

In [116]:
# using np.round() to make the data more readable.
data.round(2)

array([[ 1.  ,  1.82,  2.64,  3.45],
       [ 4.27,  5.09,  5.91,  6.73],
       [ 7.55,  8.36,  9.18, 10.  ]])

In [117]:
# np.expand_dims() will add an additional dimension to the data.
# particularly useful for when machinelearning tools don't recognize
# data because the data is in the wrong format.

# in easy terms, it turns a list into a list of lists.
# and a list of lists into a list of lists of lists (a mouthful!)

# creating an example dataset
data = np.arange(1,5)

# only a list, one-dimension.
print(data)

[1 2 3 4]


In [118]:
data_dims = np.expand_dims(data, axis=0)

# a list of lists. two-dimensions!
print(data_dims)

[[1 2 3 4]]


In [119]:
# the axis determines where the new axis position will be and how
# it wraps with the array shape.
data_dims = np.expand_dims(data, axis=1)
print(data_dims)

[[1]
 [2]
 [3]
 [4]]


In [120]:
# np.squeeze does the opposite of np.expand.dims, reducing 
# the amount of dimensions to a tensor or matrix

# creating a sample dataset
data = [[[2,2,2]]]
data = np.array(data)
print(data)

[[[2 2 2]]]


In [121]:
# np.squeeze() reduces the amount of dimensions in the np.array.
data_minus_dim = np.squeeze(data)
print(data_minus_dim)

[2 2 2]


In [122]:
# np.digitize() is used to put numbers into buckets. 
# The data goes into the closest number from the bin

data = np.array([1.6,2.6,6.1,6.8])
bins = np.array([1,2,3,4,5,6,7])

binned_data = np.digitize(data,bins)
binned_data

# this is useful because machine learning typically only takes numbers.


array([1, 2, 6, 6])